### ISSUE TITLE
Links are difficult to distinguish from normal comment text

### ISSUE THREAD

**Issue by evanrelf** [evanrelf/r-haskell-theme#1]
We could add a dotted underline below all links: 
![screen shot 2015-07-13 at 12 16 09 pm](https://cloud.githubusercontent.com/assets/887196/8658559/6c7a65ae-2959-11e5-97b8-d2ea6da79184.png)

```css
.comment .usertext a {
  border-bottom: 1px dotted gray;
}
```
